#' Summary results from the scIB project
#'
#' This dataset was generated by running the `data-raw/scib_summary.R` script.
#' This script downloads data for the RNA tasks from the
#' [scIB reproducibility repository](https://github.com/theislab/scib-reproducibility)
#' and summarises it similarly (but not exactly like) what was done in the
#' original paper to give a final ranking of the top performing methods.
#' It is used in the scIB vignette (`vignette("scIB")`) to reproduce
#' the overall summary figure in Luecken et al. 2021.
#'
#' @references
#' \insertRef{scib_Luecken2021}{funkyheatmap}
#'
#' @docType data
"scib_summary"
